### ISSUE TITLE
MGARD does not respect GNUInstallDirs

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#10]
The MGRAD package does not respect GNUInstallDirs configuration for the system.  Please use [GNUInstallDirs](https://cmake.org/cmake/help/v3.1/module/GNUInstallDirs.html) to get the installation directories in CMake so that it is installed in a consistent way across distributions.

**Comment by tugluk** [comment]
Our ADIOS2 integration team will look into this, they will probably implement it if there are no conflicts.

**Comment by ben-e-whitney** [comment]
I don't know enough about CMake to be sure, but my impression is that we haven't fixed this. Reopening till we either have or have decided against doing so. Correct me if I'm wrong!

**Comment by NAThompson** [comment]
At a minimum, writing an `install` target in the `Makefile` would be a welcome improvement. An example of how to write a nice install target is [here](https://github.com/imneme/pcg-cpp/blob/master/Makefile).

I can do this if need be, but there is deeper refactoring I'd like to do before working on this.

**Comment by robertu94** [comment]
Respectfully, the suggested Makefile fix is insufficient.  For example, It doesn't account for the presence of lib vs lib64 for the library directory on a given distribution.  Additionally, [libpressio](https://github.com/CODARCode/libpressio) depends on CMake to detect how the MGARD has been installed.

This is not to say that you can't also make a Makefile, but please fix the CMake support and do not eliminate it.

**Comment by NAThompson** [comment]
@robertu94 : There is no intention to remove CMake support.

**Comment by qliu21** [comment]
@robertu94 sorry for being late to fix this. Please can you be more specific which directories are incorrectly set for GNUInstallDirs? I will work on fixing them.

**Comment by robertu94** [comment]
@qliu21 The key issue is that you don't use the GNUInstallDirs cmake module which means that your library gets installed in non-default locations.  When linux distributions package cmake, they modify the GNUInstallDirs file to set the preferred paths for their distributions, and you don't ever check them.  The way you do it also breaks the way that GNUInstallDirs changes for certain values of "CMAKE_INSTALL_PREFIX"

You can find documentation for using it https://cmake.org/cmake/help/v3.6/module/GNUInstallDirs.html

You can find an example of it being used correctly: https://rix0r.nl/blog/2015/08/13/cmake-guide/

A few other things to fix while you are in there:

+ lines 58-60, this duplicates the functionality of "BUILD_SHARED_LIBS" and could be removed: https://cmake.org/cmake/help/v3.1/variable/BUILD_SHARED_LIBS.html#variable:BUILD_SHARED_LIBS
+ line 122: `enable_testing` is redundant if you have `include(CTest)` https://cmake.org/cmake/help/v3.15/command/enable_testing.html?highlight=enable_testing

**Comment by qliu21** [comment]
@robertu94 I will look into this and thank for providing more info. 

Just so you know. "I" didn't do the current cmake in MGARD but I would be happy to fix this, if I can reproduce the errors you mentioned.

**Comment by robertu94** [comment]
@qliu21 I apologize, I didn't mean for that to be taken as you personally.  I meant you as the plural you referring to the MGARD maintainers or whoever wrote the code.  I do however, thank you personally looking into this.

  A good example of an incompatibility is Gentoo (and I think Fedora) as well which use `/usr/lib64` instead of `/usr/lib`.

**Comment by qliu21** [comment]
I tested Fedora and it should work now for default locations. Couldn't test those duplicated CMake lines but by looking at the document you sent, it makes sense to me. @robertu94 thank you very much for the detailed the info.
