### ISSUE TITLE
linker errors when zstd not availible

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#102]
When attempting to link to mgard on a machine that does not have zstd installed, mgard produces linker errors.  Given the way mgard requests to link against zstd only if it was found, I suspect this was not intended.  Could you please clarify if zstd is required or not for new releases of mgard going forward?

**Comment by qliu21** [comment]
When ZSTD is turned off, I tried to list the symbols of the mgard .so -  It didn't seem to me that .so has any ZSTD related symbols. Please can you clarify a bit more?

**Comment by robertu94** [comment]
Sorry, this was caused by a bundled version of zstd in SZ that cmake found, but the linker couldn't find.
