### ISSUE TITLE
Additional Documentation Required

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#11]
The documentation for several overloads of the mgrad_compress function for MGARD are insufficient:

+ for example, `qoi` is documented as the "Function pointer to the quantity of interest" which is self-evident from the type signature of the function.  There is some additional information in the header "which is a bounded linear functional in s-norm", but this doesn't describe how to use this parameter.  Rather the documentation should describe how to use the parameter, and what the arguments to this function are so that the user doesn't have to read through the paper on QOI you have written and/or the source code.  
+ The compression parameter `norm_of_qoi` is undocumented completely.
+ The compression parameter `coords_{x,y,z}` are likewise undocumented
+ The decompression parameter `quantizer` is also undocumented

**Comment by robertu94** [comment]
Additionally, the `quantizer` variable seems to be unused by the implementation for `mgard_decompress`.

**Comment by tugluk** [comment]
Correct, it is a dummy argument. In future versions it will be used to return the quantizer used during compression.

norm_of_qoi is the s-norm of the quantity of interest the user wishes to use. Computable through mgard_compress 4/4a.

coords_{x,y,z} are the {x, y, z} coordinates of the underlying tensor product grid. Will add this to the documentation
