### ISSUE TITLE
find_package failure with mgard

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#112]
Recently MGARD now issues a cmake error when I go to find_package(mgard) in a seperate package.  This seems to be tied to a change in where include files are now stored.  I suspect this was unintentional:

```console
CMake Error in CMakeLists.txt:
  Imported target "mgard::mgard" includes non-existent path

    "/usr/include/mgard"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

```

The following patch fixes this:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index cfac48e..f192321 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -165,7 +165,6 @@ target_include_directories(mgard
   PUBLIC
   $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
   $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
-  $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/mgard>
 )
 target_link_libraries(mgard PRIVATE ZLIB::ZLIB  ${CMAKE_DL_LIBS})
 if(ZSTD_FOUND)
```

But I don't think this is what you want.  Instead I suspect that you want to install the include files to `$prefix/include/mgard ` rather than splatting them into `$prefix/include` where you can overwrite other files from other packages.

**Comment by qliu21** [comment]
It was intended that we write to $prefix/include.

**Comment by robertu94** [comment]
Respectfully, this issue isn't resolved.  There is still a build error that is caused by this line in CMakeLists.txt:

`$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/mgard>`

You don't have to change the installation directory, but please do change the CMakeLists.txt file to address the build error when other packages use `find_package` to load MGARD.  To reproduce the issue on your machine, you may need to temporarily remove the directory `/usr/include/mgard`

**Comment by qliu21** [comment]
We will look into this. I don't have /usr/include/mgard on my machine. And I could successfully use mgard from ADIOS. 

We are in the process of massively changing MGARD and it will take sometime. Please stay put. If you have other deadlines, please feel fix to change it in your fork while we are looking into this. thanks!

**Comment by robertu94** [comment]
I set my install prefix to `/usr/`  It might be `/include/mgard` if you have prefix set to `/` or `/usr/local/include/mgard` if it is set to `/usr/local`

**Comment by ben-e-whitney** [comment]
I 'rediscovered' this issue as part of an effort to learn CMake and clean up the build. As of 77d8dd82e898352f1613c9e2f1467886311ce818, the headers are installed to `${CMAKE_INSTALL_INCLUDEDIR}/install/mgard`. That commit hasn't been merged in to `master`, but it will be soon enough (assuming @qliu21 doesn't object!). Let us know if you run into any more problems. Thanks for the suggestions, as always.

**Comment by robertu94** [comment]
Thanks @ben-e-whitney could you @ me on the PR you you make it so I can update libpressio accordingly.
