### ISSUE TITLE
please provide version macros, and update them with changes

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#12]
libpressio needs to be able to access version information about what version of mgard it was compiled with so it can call the right functions in the mgard plugin, but there is no version information exposed in the public API at compile time (i.e. as a version macro or function).  This is needed to switch between implementations of the API depending on what is installed.

Additionally, the last major release of MGARD was 0.0.0.2 and the version number was not updated when the new version was released.  This number needs to be incremented at least when APIs are removed as they were with the current release.

**Comment by tugluk** [comment]
Our productization team will look ito this

**Comment by ben-e-whitney** [comment]
Reopening till we've either added the macros or decided against doing so.

**Comment by qliu21** [comment]
Fixed. The mgard installation should contain MGARDConfig.h in include for version number.
