### ISSUE TITLE
Combining and Renaming `mgard_api.h` and `mgard_api_cuda.h`

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#124]
Before the next release, I propose we combine `mgard_api.h` and `mgard_api_cuda.h` and rename to `mgard.hpp`, `api.hpp`, `compress.hpp`, or something else. Pros:

* All of the other headers the user might want to include (`TensorMeshHierarchy.hpp`, `TensorQuantityOfInterest.hpp`, `TensorNorms.hpp`, etc.) have the extension `.hpp`.
* The (CPU) functions are contained in the `mgard` namespace, and the headers are installed to an `mgard` subdirectory as of 927f867d0780c5ccb0ff7b264e2eab6f39fad0ca, so the `mgard_` prefix is redundant. I guess this is an argument against `mgard.hpp`.
* The functions in `mgard_api.h` and `mgard_api_cuda.h` differ in implementation, not purpose, so I think it makes sense to declare them in the same header.

Cons:

* Users will have to change their code.
* Users would be unable to include only the CPU or only the GPU functions.

**Comment by cjy7117** [comment]
I'm fine with merging these two header files. One thing to note: Just in case users built the MGARD library without GPU but accidentally call the GPU version API, we need to decide what to do: 1) give an error message and stop the program; or 2) give a warning message and fall back to the CPU version.

**Comment by cjy7117** [comment]
@ben-e-whitney, When I try to include ```mgard_api.h``` to my test program after I added my GPU APIs in there I get the following compilation error. Do you have any idea what is wrong?
```
/home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:234:29: error: ‘__T0’ was not declared in this scope
     const CartesianProduct<T, N> &iterable,
                             ^~~~
/home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:234:29: note: suggested alternative: ‘__y0’
     const CartesianProduct<T, N> &iterable,
                             ^~~~
                             __y0
/home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:234:36: error: template argument 1 is invalid
     const CartesianProduct<T, N> &iterable,
                                    ^
/home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:233:1: error: prototype for ‘mgard::CartesianProduct<T, N>::iterator::iterator(const mgard::CartesianProduct<T, N>&, int)’ does not match any in class ‘mgard::CartesianProduct<T, N>::iterator’
 CartesianProduct<T, N>::iterator::iterator(
 ^~~~~~~~~~~~~~~~~~~~~~~
/home/jieyang/dev/MGARD-release/MGARD/include/utilities.hpp:348:1: error: candidate is: mgard::CartesianProduct<T, N>::iterator::iterator(const mgard::CartesianProduct<T, N>&, std::array<decltype (declval<typename std::array<_Tp, _Nm>::const_reference>().begin()), N>)
   iterator(const CartesianProduct &iterable,
 ^ ~~~~~~
```

**Comment by ben-e-whitney** [comment]
@cjy7117: I made a new issue for that: #126.
