### ISSUE TITLE
Template Errors After Adding GPU APIs to `mgard_api.h`

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#126]
@cjy7117 reported the following in #124. (I rewrapped the error message.)

> @ben-e-whitney, When I try to include `mgard_api.h` to my test program after I added my GPU APIs in there I get the following compilation error. Do you have any idea what is wrong?
> 
> ```
> /home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:234:29: error:
> ‘__T0’ was not declared in this scope
>      const CartesianProduct<T, N> &iterable,
>                              ^~~~
> /home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:234:29: note:
> suggested alternative: ‘__y0’
>      const CartesianProduct<T, N> &iterable,
>                              ^~~~
>                              __y0
> /home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:234:36: error:
> template argument 1 is invalid
>      const CartesianProduct<T, N> &iterable,
>                                     ^
> /home/jieyang/dev/MGARD-release/MGARD/include/utilities.tpp:233:1: error:
> prototype for
> ‘mgard::CartesianProduct<T, N>::iterator::iterator(const mgard::CartesianProduct<T, N>&, int)’
> does not match any in class ‘mgard::CartesianProduct<T, N>::iterator’
>  CartesianProduct<T, N>::iterator::iterator(
>  ^~~~~~~~~~~~~~~~~~~~~~~
> /home/jieyang/dev/MGARD-release/MGARD/include/utilities.hpp:348:1: error:
> candidate is:
> mgard::CartesianProduct<T, N>::iterator::iterator(
>     const mgard::CartesianProduct<T, N>&,
>     std::array<decltype (declval<typename std::array<_Tp, _Nm>::const_reference>().begin()), N>
> )
>    iterator(const CartesianProduct &iterable,
>  ^ ~~~~~~
> ```

I'm going to focus on the second error to start. It looks like a `CartesianProduct<T, N>::iterator` is getting constructed incorrectly somewhere. @cjy7117, does this error get thrown on a particular part of the test program? I need to be able to reproduce the error.

**Comment by cjy7117** [comment]
@ben-e-whitney , actually I got this error even if I don't merge the GPU API. When I try to include original ```mgard_api.h``` in my test program ```../src/cuda/mgard_cuda_double_test.cu```, I get this error when compiling.

**Comment by cjy7117** [comment]
@ben-e-whitney Yes, I can reproduce this problem. I can modify my GPU design such that users do not need to use ```nvcc``` to compile their source code when linked with the MGARD-GPU library. However, if the users' source code is for GPU (e.g., if they use MGARD in a simulation code that runs on GPU), then they must use ```nvcc``` which would still trigger the bug.

**Comment by cjy7117** [comment]
@ben-e-whitney I try to work around this bug by keeping both ```mgard_api.h``` and ```mgard_cuda_api.h``` headers. The GPU APIs are included in both header files. The difference between the two is that when users compile their code with C/C++ compiler, they should use ```mgard_api.h```  and if they to NVCC then they should use ```mgard_cuda_api.h```.

**Comment by ben-e-whitney** [comment]
I asked the OLCF User Assistance Center for help with this back in April (ticket number OLCFHELP-1720). They reproduced the error and asked their internal Nvidia contact for help. That person opened another ticket (with Nvidia?) and reported back:

> Someone pointed out that it looks like another issue they were already actively tracking. They are already working on a fix. It may be a little bit until it makes it into a public release, but I’ll keep tracking it and let you know.

So it looks like eventually this will get fixed. In the meantime, we can use your solution of keeping both headers.
