### ISSUE TITLE
Installation dir for header files

### ISSUE THREAD

**Issue by cjy7117** [CODARcode/MGARD#127]
I'm trying to mimic what a general user would do to use MGARD:

- Build and install MGARD
- Build a test separate test program that uses MGARD.

However, I'm getting issues when compiling my test program since the compiler could not find the header files. This is because when we develop MGARD the header files are in ```../include/*``` and when installed the header files are in ```../include/mgard/*```. When I use cmake to link target with library ```mgard::mgard```, it uses ```gcc ... -I <install_dir>/include ```, so it cannot find header files. Could we make changes to the relative header directories so that both the developing and installing directories are consistent?

**Comment by ben-e-whitney** [comment]
I think installing the headers to `<install_dir>/include/mgard` and telling the compiler to look in `<install_dir>/include` is right (see #112), so we should change the build interface paths to match by moving the headers from `include` to `include/mgard`. Would that fix the problem? That seems to be how ADIOS does it (see [here][ADIOS include] and, for example, [here][ADIOS header]).

[ADIOS include]: https://github.com/ornladios/ADIOS2/tree/v2.7.0/source
[ADIOS header]: https://github.com/ornladios/ADIOS2/blob/2ceb04834572492b725525efa3e97887dbbae09e/source/adios2/core/ADIOS.h#L21-L24

**Comment by cjy7117** [comment]
Yes. I think moving all headers files from ```include``` to ```include/mgard``` should work for me. I can create a PR for moving headers for the GPU version. I will leave the CPU part unchanged since I don't want to break your code. There will be two include paths for the build interface (```$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>```  and ```$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/mgard>```) temporarily. You can remove the old one once the headers for the CPU version are moved.  Is that ok?

**Comment by cjy7117** [comment]
@ben-e-whitney , I have figured out a way to solve this problem without having to move the header files. I will create the PR for this.

**Comment by ben-e-whitney** [comment]
Did you open a pull request? I can't find it. I'm happy to move the CPU headers – it's no big deal.

**Comment by cjy7117** [comment]
@ben-e-whitney I have resolved the problem so that we do not need to move CPU and GPU headers. See PR #128.
