### ISSUE TITLE
How are overloads 4 and 5 of mgard compress intended to be used?

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#13]
Overloads 4 and 5 of `mgard_compress` have different return types and no outsize parameter compared to the other overloads provided.  The documentation states that the returned value can be used for future datasets, but it doesn't say how.  Could you please elaborate?  

Perhaps it should have a different function name since it doesn't do the same thing?

**Comment by tugluk** [comment]
These routines  compute the  s-norm of a quantity of interest.  If the user wishes to reuse the qoi, the can be passed to 6 as norm_of_qoi
