### ISSUE TITLE
MGARD segfaults on some inputs

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#15]
MGRAD segfaults on the some inputs,  I ran with: [the dataset generated from this function](https://github.com/CODARcode/libpressio/blob/master/test/make_input_data.cc), a tolerance of 0.5, and a s of 1.0 using the double api and I get a segfault.

Other inputs (i.e. tolerance of .5 and s of 8.0; as well as tolerance of .5 and default s) seem to work, but are very slow (10x SZ, and 5x ZFP) and have poor PSNR, MSE, and other error statistics.  

I would appreciate any guidance you can offer on how I should be using your compressor.

**Comment by tugluk** [comment]
A tolerance of 0.5 means %50 error so poor PSNR, MSE is as expected.  If you can provide the data set we will try to replicate the issue

**Comment by tugluk** [comment]
Ran the user included code (please provide datafile next time if possible), cannot replicate segfault through the supplied example binary.

**Comment by robertu94** [comment]
This is part of the libpressio test_case (specifically the "full" integration test).  MGARD is configured [here](https://github.com/robertu94/libpressio/blob/c9f5d64ad836d5a8709e0d239cb3b93b2cfc3dd3/test/full.c#L183).

The ultimate calls for compression appear in the [mgard plugin on lines 151-227](https://github.com/robertu94/libpressio/blob/c9f5d64ad836d5a8709e0d239cb3b93b2cfc3dd3/src/plugins/compressors/mgard_plugin.cc#L151)

The ultimate calls for decompression appear in the [mgard plugin on lines 230-265](https://github.com/robertu94/libpressio/blob/c9f5d64ad836d5a8709e0d239cb3b93b2cfc3dd3/src/plugins/compressors/mgard_plugin.cc#L230)

I'd be happy to provide a singularity container with everything installed if that would help you reproduce.  Alternatively, I'd be happy to help you get libpressio installed and configured.

**Comment by tugluk** [comment]
This is curious, as the parameter "s" is not used until very late in the code and there should absolutely be no difference between different values. We are assuming somehow a double method is triggered on float data. Can the user provide info on whether the segfault is in compression or decompression?

**Comment by robertu94** [comment]
@tugluk I've tried this, and we are correctly dispatching to the float version of the method for both the float and double case.  There are a few different segfaults, but the one that I can reproduce right now is: After compression, the pointer returned points to invalid memory, i.e. it segfaults in `memcpy` in the following code sample

```c
int outsize = 0;
compressed = mgard_compress(itype, float_data, outsize, dim0, dim1, dim2, tolerance)
assert(compressed != nullptr);
assert(outsize != 0);
auto copy = new char[outsize];
memcpy(copy, compressed, outsize);
```

**Comment by ben-e-whitney** [comment]
This has been fixed in the reimplemented `compress` function added to the API in 1120e92e4e9bf96cbacb9fd0f796456f9986028c. Unzip [this archive][issue_15.zip] in the root of the repository and run the following.

```console
$ make lib/libmgard.a bin/ --jobs 8
$ g++ -g -fno-omit-frame-pointer -O3 -march=native -ffast-math -fno-finite-math-only -std=c++11 -fPIC -Iinclude  -c -o obj/issue_15.o issue_15.cpp
$ g++ -g -fno-omit-frame-pointer -O3 -march=native -ffast-math -fno-finite-math-only    obj/issue_15.o lib/libmgard.a -lz -ldl -o bin/issue_15
$ bin/issue_15
size of compressed dataset is 638272 bytes
```

I'll leave this issue open till the changes have been merged. Let me know if there are any other problems with this.

[issue_15.zip]: https://github.com/CODARcode/MGARD/files/5263233/issue_15.zip
