### ISSUE TITLE
Config parameter of mgard_cuda::compress/decompress not optional

### ISSUE THREAD

**Issue by kmorel** [CODARcode/MGARD#161]
The [documentation for MGARD-GPU](https://github.com/CODARcode/MGARD/blob/master/doc/MGARD-GPU.md) states that the `config` parameter is supposed to be optional for `compress` and `decompress`. However, it is not optional for either of them and you get a compile error if you leave it out.

On a mostly unrelated note, there is another error in the documentation of `mgard_cuda::compress` where the documentation for the `original_data` and `compressed_data` arguments are conflated.

**Comment by JieyangChen7** [comment]
#166 should fix this issue.
