### ISSUE TITLE
Unable to compile or link library with the provided simple example. 

### ISSUE THREAD

**Issue by hengjiew** [CODARcode/MGARD#184]
Hello guys,

This issue is related to issue #182. I can now build mgard with cuda 11.4.2 on Summit, provided that I installed all the dependencies manually. I tried to compile the example provide at https://github.com/CODARcode/MGARD/blob/master/doc/MGARD-X.md. The compilation works fine but I got missing reference during the linkage 
```
test_mgard.o: In function `main':
tmpxft_002109dc_00000000-6_test_mgard.cudafe1.cpp:(.text+0x19c): undefined reference to `mgard_x::Array<3u, double, mgard_x::CUDA>::load(double const*, unsigned int)'
tmpxft_002109dc_00000000-6_test_mgard.cudafe1.cpp:(.text+0x208): undefined reference to `mgard_x::Array<1u, unsigned char, mgard_x::CUDA> mgard_x::compress<3u, double, mgard_x::CUDA>(mgard_x::Hierarchy<3u, double, mgard_x::CUDA>&, mgard_x::Array<3u, double, mgard_x::CUDA>&, mgard_x::error_bound_type, double, double)'
tmpxft_002109dc_00000000-6_test_mgard.cudafe1.cpp:(.text+0x218): undefined reference to `mgard_x::Array<1u, unsigned char, mgard_x::CUDA>::shape()'
tmpxft_002109dc_00000000-6_test_mgard.cudafe1.cpp:(.text+0x298): undefined reference to `mgard_x::Array<3u, double, mgard_x::CUDA> mgard_x::decompress<3u, double, mgard_x::CUDA>(mgard_x::Hierarchy<3u, double, mgard_x::CUDA>&, mgard_x::Array<1u, unsigned char, mgard_x::CUDA>&)'
collect2: error: ld returned 1 exit status
```
I double-checked that libmgard.so is in the library path and passed to nvcc. Maybe I am wrong about this, but some functions seem not built into the library. For instsance, if I do `nm -D libmgard.so | grep -i marg_x | grep -i shape` , it only outputs
```
00000000010f70f0 T _ZN7mgard_x11infer_shapeEPKvm
```
The function  mgard_x::Array<...>.shape() is not there. 

Also could you please confirm if the example in  `/examples/mgard-x/SimpleExample` is up to date? It misses the header `mgard/compress_x.hpp` and some functions seem not to match the declarations in `mgard-x/RuntimeX/DataStructures/Array.h`.

**Comment by JieyangChen7** [comment]
@hengjiew The provided example code for low-level API is outdated. I will update it in the near future.

**Comment by hengjiew** [comment]
> @hengjiew The provided example code for low-level API is outdated. I will update it in the near future.

Thanks for the confirmation. 
Could you please point me to an up-to-date example with a compression followed by a decompression? Either lower or higher API will work. 

Also, do I suppose to use the mgard_x::Array class? or it's not compiled into the library? Thanks!
