### ISSUE TITLE
Cannot build MGARD

### ISSUE THREAD

**Issue by lindstro** [CODARcode/MGARD#185]
I just fetched the latest MGARD commits, but am having build issues:
```
-- Checking for one of the modules 'protobuf>=3.0.0'
CMake Error at /usr/local/Cellar/cmake/3.22.3/share/cmake/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'protobuf>=3.0.0' found
```
This in spite of having protobuf 3.19.4 installed:
```
% brew info protobuf
protobuf: stable 3.19.4 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/protocolbuffers/protobuf/
/usr/local/Cellar/protobuf/3.19.4 (270 files, 19.6MB) *
  Poured from bottle on 2022-03-12 at 07:46:11
```
Any suggestions would be appreciated.

**Comment by ben-e-whitney** [comment]
Hi @lindstro. I don't have a Mac to reproduce this on, but I'll still suggest a few things to try. Later on in the week we'll get someone with a Mac (@JieyangChen7?) to look into it.

CMake is using `pkg-config` to find Protobuf. To do that, `pkg-config` needs to find a configuration file called `protobuf.pc`. My guess is that either the Homebrew Protobuf formula doesn't provide `protobuf.pc` or it does provide it but puts it somewhere CMake doesn't know to look.

I have tried following the Protobuf formula [here][Protobuf formula]. For me, the Protobuf library is installed to `${PREFIX}/lib/libprotobuf.a` and the `pkg-config` configuration file is installed to `${PREFIX}/lib/pkgconfig/protobuf.pc`. So, I suggest you try the following:

1. Find where the Protobuf library has been installed. Suppose it's at `${PREFIX}/lib/libprotobuf.so`.
2. Look in the same tree for `protobuf.pc`. Again, for me it's at `${PREFIX}/lib/pkgconfig/protobuf.pc`.
3. Check that `pkg-config` is able to find `protobuf.pc` when given the (immediate) parent directory containing it. The following works for me.

```console
$ PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" pkg-config --print-provides protobuf
protobuf = 3.19.4
```
4. Tell CMake to look in `${PREFIX}` with `-D CMAKE_PREFIX_PATH="${HOME}"`. The following works for me.

```console
$ cmake -S . -B build -D CMAKE_PREFIX_PATH="${PREFIX}"
```

If that doesn't work, maybe try `-D CMAKE_PREFIX_PATH="${PREFIX}/lib"` or `-D CMAKE_PREFIX_PATH="${PREFIX}/lib/pkgconfig` (or whatever the parent directories of your `protobuf.pc` are).

5. Let us know if that doesn't work!

[Protobuf formula]: https://github.com/Homebrew/homebrew-core/blob/9b5641b33145149d3c873ecced3c2f535d20a8a5/Formula/protobuf.rb

Sorry for the trouble, and thanks very much for reporting the problem.

**Comment by lindstro** [comment]
@ben-e-whitney That did it!  Unfortunately, the documentation does not build on my Mac (`/usr/bin/sed: illegal option -- -`), so I'm not sure how to use the CLI.  Is there a reasonable default for the "smoothness" parameter?  How do I specify the dimensions of multidimensional arrays?

**Comment by ben-e-whitney** [comment]
@lindstro Oh, it must be a GNU `sed` vs. BSD `sed` thing. I will fix that later this week.

I would keep the smoothness parameter at 0. Then the error will be controlled in the L² norm. You can specify the dimensions of an array like this: `--shape 40x50x60`. The dimensions are in C order: the first `n` bytes of the input file will be `u[0][0][0]`, then `u[0][0][1]`, …, then `u[0][0][59]`, then `u[1][0][0]`, etc.

You can get some basic documentation with these commands:

```console
$ mgard --help
$ mgard compress --help
$ mgard decompress --help
$ man mgard
```
Feel free to just ask, though. It will help us know where to add documentation.

**Comment by lindstro** [comment]
Thanks, this helps.  How should the "absolute error tolerance" parameter be interpreted?  Using a smoothness parameter of 0, does it bound the L<sup>2</sup> or L<sup>&infin;</sup> error?  The observed L<sup>&infin;</sup> error exceeds the tolerance, so I'm guessing the former.  Is it possible to bound the L<sup>&infin;</sup> error?

**Comment by ben-e-whitney** [comment]
Yes, L² in that case. The smoothness parameter selects the norm in which the error will be controlled. The absolute error tolerance is the largest the error will be in that norm. So if you used `--smoothness 0 --tolerance 0.1`, you'd be guaranteed

```
‖ u − ũ ‖_L² ≤ 0.1
```
where `u` is the original dataset and `ũ` is the compressed dataset. _Absolute_ in contrast to _relative_ – the righthand side is `0.1`, not `0.1 * ‖ u ‖_L²`.

To bound the error in the L<sup>&infin;</sup> norm, use `--smoothness inf`. (In case you're ever referring to the papers, this is a kind of notational kludge. 'Smoothness parameter' is `s` in the papers, but `s` is never infinity. Following the papers, the CLI should do something like `--norm Linf` for L<sup>&infin;</sup> and `--norm sobolev --norm-smoothness-parameter 0` for L².)

As you will soon find out, the L<sup>&infin;</sup> error bound is generally quite pessimistic. You might ask for an error of `1e-3` but get an error of `1e-4`. A few reasons:

1. The L<sup>&infin;</sup> norm is kind of an unnatural fit for the decomposition used by MGARD.
2. The relevant error bounds are not as good as they could be.
3. The way the transform coefficients are quantized forces the error analysis to accommodate a particularly bad worst case scenario.

There is some (slow) progress on the second and third points. In practice, if I were using this now, I'd run a bunch of tests till I could say, 'Empirically, for my data, if I want error `τ`, I ask for error `α * τ`.'

**Comment by lindstro** [comment]
> As you will soon find out, the L∞ error bound is generally quite pessimistic. You might ask for an error of `1e-3` but get an error of `1e-4`. A few reasons:
> 
> 1. The L∞ norm is kind of an unnatural fit for the decomposition used by MGARD.
> 2. The relevant error bounds are not as good as they could be.
> 3. The way the transform coefficients are quantized forces the error analysis to accommodate a particularly bad worst case scenario.

Those same reasons apply to zfp. :-)  Suppose I don't care about the error bound being loose, e.g., I might plot a rate-distortion curve and then select the rate and/or distortion that suit my needs.  In this case, does it matter which error norm is being optimized?  In other words, does the MGARD compression algorithm make different decisions depending on the type of error norm?

**Comment by ben-e-whitney** [comment]
Apologies for the delay!

> In other words, does the MGARD compression algorithm make different decisions depending on the type of error norm?

Yes, it does. The error norm affects the quantization of the decomposition coefficients (but not the decomposition itself).

Background: Each decomposition coefficient represents a 'wiggle' in the data which looks something like `α · exp(−β · (x − x₀)) · cos(β · (x − x₀))`. The parameters:

* The amplitude `α` is determined by the magnitude of the coefficient.
* The center `x₀` is determined by the position of the coefficient in the coefficient array.
* The frequency `β` is determined by the level in the mesh hierarchy that the coefficient 'lives' on.

Quantization differences:

1. As `β → ∞`, the wiggle's L<sup>&infin;</sup> norm stays constant but its L² norm goes to zero. So, coefficients with larger `β` are quantized more aggressively when using the L² norm but not when using the L<sup>&infin;</sup> norm. In the papers, this explains the `vol(P_{l})` term found [[here][qoi], Lemma 2.2] but not [[here][multivariate], Eq. (8)]. In the code, it explains the `volume_factor` term found [here][s_quantum] but not [here][supremum_quantum].
2. The `s` norms are more or less sensitive to wiggles with high frequency depending on the value of `s`. If `s > 0`, wiggles with high `β` are given greater weight. If `s < 0`, they're given lesser weight. So, coefficients with large `β` are quantized more aggressively if `s < 0` and less aggressively if `s > 0`. See the `2^{2 s l}` terms [[here][qoi], Eq. (2) and Lemma 2.2] and the `std::exp2(s * l)` term [here][s_quantum].

[multivariate]: https://doi.org/10.1137/18M1166651
[qoi]: https://doi.org/10.1137/18M1208885
[s_quantum]: https://github.com/CODARcode/MGARD/blob/70d3399f6169c8a369da9fe9786c45cb6f3bb9f1/include/TensorMultilevelCoefficientQuantizer.tpp#L36-L54
[supremum_quantum]: https://github.com/CODARcode/MGARD/blob/70d3399f6169c8a369da9fe9786c45cb6f3bb9f1/include/TensorMultilevelCoefficientQuantizer.tpp#L11-L25

**Comment by lindstro** [comment]
Thanks for the explanation.  But aren't the basis functions modulated Gaussians?  I suspect there's a square missing in the expression for the 'wiggle'.

**Comment by ben-e-whitney** [comment]
No. I think you must be thinking of some other method. Maybe something using radial basis functions? In MGARD the *actual* basis is `{(I − Q_{l − 1}) φ_{l}(·; x) : 0 ≤ l ≤ L and x ∈ N_{l} \ N_{l − 1}}` where

* `l` is the index of some mesh in the mesh hierarchy (`L` is the index of the finest mesh);
* `N_{l}` is the set of nodes in mesh `l`, so that `N_{l} \ N_{l − 1}` is the set of 'new' nodes in mesh `l`;
* `φ_{l}(·; x)` is a piecewise linear 'hat function' that is one at `x` and zero at every other node in `N_{l}`;
* `Q_{l − 1}` is the L² projection 'onto mesh `l − 1`' (onto the space of continuous piecewise functions with knots `N_{l − 1}`); and
* `I` is the identity.

See [[here][multivariate], p. A1282]. Each `(I − Q_{l − 1}) φ_{l}(·; x)` oscillates and decays exponentially away from `x`. The spacing between the nodes in level `l` determines

1. the rate of decay (which determines the L² norm of the wiggle) and
2. the frequency of the oscillations (which determines the weighting in the `s` norms).

In my previous post, 'large `β`' should really be 'large `l`'. I was just trying to give the intuition!

[multivariate]: https://doi.org/10.1137/18M1166651

The basis functions look like this:

![image](https://user-images.githubusercontent.com/5350974/159730097-dda038e1-9c25-4111-8edc-609ce748ddaf.png)

Here's the code used to make that plot:

```python3
import numpy as np

import scipy as sp
import scipy.sparse
import scipy.sparse.linalg

import matplotlib as mpl
import matplotlib.figure

colors = mpl.cm.get_cmap('tab10').colors

DOMAIN_SIZE = 1

class Mesh:
    #Number of nodes in the fine mesh.
    n_fine: int
    #Number of nodes in the coarse mesh.
    n_coarse: int
    #Number of nodes in the coarse mesh minus 1.
    N: int

    def __init__(self, n_fine: int) -> None:
        assert n_fine % 2
        self.n_fine = n_fine
        self.n_coarse = self.n_fine // 2 + 1

    #`N_{l - 1}`.
    def nodes_coarse(self) -> np.ndarray:
        return np.linspace(0, DOMAIN_SIZE, num=self.n_coarse)

    #`N_{l}`.
    def nodes_fine(self) -> np.ndarray:
        return np.linspace(0, DOMAIN_SIZE, num=self.n_fine)

    #`N_{l} \ N_{l - 1}`.
    def nodes_new(self) -> np.ndarray:
        #Every other fine node.
        return self.nodes_fine()[1 :: 2]

def _mass_matrix(n: int, m: int) -> sp.sparse.spmatrix:
    if n < 2:
        raise ValueError(f'Mesh must have at least two nodes (n = {n}).')
    diagonals = np.empty((3, n))
    diagonals[: 2, :] = 1
    diagonals[2, 0] = 2
    diagonals[2, 1 : -1] = 4
    diagonals[2, -1] = 2
    h = DOMAIN_SIZE / (n - 1)
    return sp.sparse.dia_matrix((h / 6 * diagonals, (-1, 1, 0)), shape=(n, n))

def mass_matrix_fine(mesh: Mesh) -> sp.sparse.linalg.LinearOperator:
    return sp.sparse.linalg.aslinearoperator(
        _mass_matrix(mesh.n_fine, mesh.n_fine)
    )

def mass_matrix_coarse(mesh: Mesh) -> sp.sparse.linalg.LinearOperator:
    return sp.sparse.linalg.aslinearoperator(
        _mass_matrix(mesh.n_coarse, mesh.n_coarse)
    )

def _interpolation_matrix(n: int, m: int) -> sp.sparse.spmatrix:
    if n < 2:
        raise ValueError(f'Mesh must have at least two nodes (n = {n}).')
    nnz = 3 * n - 2
    data = np.empty((nnz,))
    i = np.empty((nnz,), dtype=int)
    j = np.empty((nnz,), dtype=int)
    data[: n] = 1
    j[: n] = range(n)
    i[: n] = 2 * j[: n]
    data[n :] = 0.5
    for j_ in range(1, n - 1):
        s = slice(n + 2 * j_ - 2, n + 2 * j_)
        j[s] = j_
        i[s] = (2 * j_ - 1, 2 * j_ + 1)
    j[-2] = 0
    i[-2] = 1
    j[-1] = n - 1
    i[-1] = m - 2
    return sp.sparse.coo_matrix((data, (i, j)), shape=(m, n))

def interpolation_matrix(mesh: Mesh) -> sp.sparse.linalg.LinearOperator:
    return sp.sparse.linalg.aslinearoperator(
        _interpolation_matrix(mesh.n_coarse, mesh.n_fine)
    )

def _restriction_matrix(m: int, n: int) -> sp.sparse.spmatrix:
    return _interpolation_matrix(n, m).T

def restriction_matrix(mesh: Mesh) -> sp.sparse.linalg.LinearOperator:
    return sp.sparse.linalg.aslinearoperator(
        _restriction_matrix(mesh.n_fine, mesh.n_coarse)
    )

def projection_matrix(mesh: Mesh) -> sp.sparse.linalg.LinearOperator:
    M_fine: sp.sparse.linalg.LinearOperator = mass_matrix_fine(mesh)
    M_coarse_: sp.sparse.csc_matrix = \
        _mass_matrix(mesh.n_coarse, mesh.n_coarse).tocsc()
    R: sp.sparse.linalg.LinearOperator = restriction_matrix(mesh)

    def inner(v: np.ndarray) -> np.ndarray:
        return sp.sparse.linalg.spsolve(M_coarse_, R @ M_fine @ v)

    return sp.sparse.linalg.LinearOperator(
        shape=(mesh.n_coarse, mesh.n_fine),
        dtype=float,
        matvec=inner
    )

def identity_matrix(mesh: Mesh) -> sp.sparse.linalg.LinearOperator:
    return sp.sparse.linalg.aslinearoperator(sp.sparse.eye(mesh.n_fine))

def hat_function(mesh: Mesh, i: int) -> np.ndarray:
    #Hat function centered at node `i` (fine index).
    phi: np.ndarray = np.zeros((mesh.n_fine,))
    phi[i] = 1
    return phi

mesh = Mesh(21)
I = identity_matrix(mesh)
#Project from the fine mesh to the coarse mesh, then interpolate back up to the
#fine mesh.
Q = interpolation_matrix(mesh) @ projection_matrix(mesh)

i: int = 7
#The nodes of the fine mesh have odd indices.
assert i % 2
phi = hat_function(mesh, i)

xs_fine: np.ndarray = mesh.nodes_fine()
xs_coarse: np.ndarray = mesh.nodes_coarse()
xs_new: np.ndarray = mesh.nodes_new()

fig = mpl.figure.Figure()
axes = fig.add_subplot(1, 1, 1)
axes.plot(
    xs_coarse,
    np.zeros_like(xs_coarse),
    color='black',
    marker='s',
    markersize=5,
    linestyle='none',
    label='node in $N_{l - 1}$',
)
axes.plot(
    xs_new,
    np.zeros_like(xs_new),
    color='black',
    marker='s',
    markersize=4,
    markerfacecolor='none',
    linestyle='none',
    label='node in $N_{l} ∖ N_{l - 1}$',
)
axes.plot(
    xs_fine,
    phi,
    color=colors[0],
    linestyle='dashed',
    label='$\phi_{l}(\cdot; x)$',
)
axes.plot(
    xs_fine,
    Q @ phi,
    color=colors[1],
    linestyle='dotted',
    label='$Q_{l - 1} \phi_{l}(\cdot; x)$',
)
axes.plot(
    xs_fine,
    (I - Q) @ phi,
    color=colors[2],
    label='$(I - Q_{l - 1}) \phi_{l}(\cdot; x)$',
)
axes.legend()
fig.savefig('basis_function.png', dpi=300)
```

**Comment by lindstro** [comment]
Thanks for your help.
