### ISSUE TITLE
`MGARD_ENABLE_CUDA` variable not exported

### ISSUE THREAD

**Issue by anagainaru** [CODARcode/MGARD#212]
I need to know if MGARD was build with CUDA support to enable testing in ADIOS2 using GPU buffers (it is not enough to check if MGARD is enabled).  Is it possible to export the `MGARD_ENABLE_CUDA` variable?

**Comment by JieyangChen7** [comment]
Sure. I can export the variable. I will let you know when it is done.

**Comment by JieyangChen7** [comment]
I just remember that we already exported `MGARD_ENABLE_CUDA` variable. If you include `<install_dir>/include/mgard/mgard-x/RuntimeX/MGARDXConfig.h`, you should be able to use `#if MGARD_ENABLE_CUDA` to check if MGARD is built with CUDA.

**Comment by anagainaru** [comment]
Thanks @JieyangChen7 let me double check today before you close the issue
