### ISSUE TITLE
Error calculator data type problem

### ISSUE THREAD

**Issue by jpcoding** [CODARcode/MGARD#231]
https://github.com/CODARcode/MGARD/blob/master/include/mgard-x/Utilities/ErrorCalculator.h

Hi,

Should the error statistics inside this file be changed to double (or even longer if necessary) instead of T. The additions here could introduce some errors here from some tests when the original data and the decompressed data type is single precision. 

template <typename T>
T MSE(size_t n, const T *original_data, const T *decompressed_data) {
  T mse = 0;
  for (size_t i = 0; i < n; ++i) {
    T temp = fabs(original_data[i] - decompressed_data[i]);
    mse += temp * temp;
  }
  return mse / n;
}

**Comment by JieyangChen7** [comment]
Thanks! We will fix this in PR #233.
