### ISSUE TITLE
How do I determine how big my compressed data is?

### ISSUE THREAD

**Issue by NAThompson** [CODARcode/MGARD#27]
When I call `mgard_compress` on a vector of length `n`, then I obtain an `unsigned char*`. How do I know how long the data is that the `unsigned char*` points to?

**Comment by qliu21** [comment]
@NAThompson @ben-e-whitney The "int &out_size" argument?

**Comment by ben-e-whitney** [comment]
The README says the `out_size` parameter tells you that. Is it not getting set? (Incidentally, its type is `int *` in the README but `int &` in the [float][float API] and [double][double API] headers.)

[float API]: https://github.com/CODARcode/MGARD/blob/master/include/mgard_api_float.h
[double API]: https://github.com/CODARcode/MGARD/blob/master/include/mgard_api.h

**Comment by NAThompson** [comment]
Ok, it looks like by default the pointer is leaked, so we need to document how to destroy the `malloc`'d memory. In addition, it looks like there is no reason for this, since if you look at `mgard.cpp`, line 65:

```
 std::vector<unsigned char> out_data;

  mgard::compress_memory_z(qv.data(), sizeof(int) * qv.size(), out_data);

  outsize = out_data.size();
  unsigned char *buffer = (unsigned char *)malloc(outsize);
  std::copy(out_data.begin(), out_data.end(), buffer);
  return buffer;
```

So ostensibly we could just return `out_data` as a vector which would obviate the `std::copy` and get rid of the memory leak.

@ben-e-whitney : I've fixed the typo in the `README.md`.

**Comment by qliu21** [comment]
@NAThompson @ben-e-whitney I did notice some issues with the API (what is the new master right now), especially for decompression. Perhaps let's move this to a new thread - I would like to get this addressed this after SC19 (the end of Nov).

**Comment by ben-e-whitney** [comment]
FYI: the reimplemented compress function added in 1120e92e4e9bf96cbacb9fd0f796456f9986028c returns an object which knows the size of the compressed dataset.

```cpp
const mgard::CompressedData<N, Real> compressed = mgard::compress(hierarchy, u, s, tolerance);
std::cout << "the size of the compressed dataset is " << compressed.size() << " bytes" << std::endl;
```
