### ISSUE TITLE
Pruning Old Branches

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#34]
I think we can clean up the repository by deleting some old branches. The branches:

* `fpic`: Fully merged.
* `mgard`: *Not* fully merged. Contains five commits by @tugluk and @NAThompson not in `master`.
* `mgard3`: *Not* fully merged. Contains two commits by @tugluk not in `master`. As far as I can tell, 21a2f39b2496386163743a47906016affd813b72 should be merged while 01857c3ea316f3d0e3919cd752ce51b3ee84cc9e can be dropped (it makes changes to the `README`, which has since been rewritten).
* `perf1`: Fully merged.
* `qoi`: *Not* fully merged. Contains one commit by @tugluk not in `master`. I think it can be dropped, though, as the namespace it renames (`mgard_cannon` to `mgard_canon`) has since been renamed again.
* `vanilla`: Fully merged.

I propose we

* delete `fpic`, `perf1`, and `qoi`;
* merge 21a2f39b2496386163743a47906016affd813b72 from `mgard3` and all of `mgard`; and
* keep `vanilla` as the release @tugluk (Brown, generally) is responsible for (assuming that's the purpose of that branch).

Thoughts? It can wait till after SC19.

**Comment by tugluk** [comment]
@ben-e-whitney : No need to merge anything from mgard3, or qoi. I am working on master so I wouldn't mind if anything else gets nuked :)

**Comment by qliu21** [comment]
@ben-e-whitney Please can you confirm with the Brown team that fpic and qoi can be deleted? Thank you!

**Comment by ben-e-whitney** [comment]
@tugluk says they can be deleted.

**Comment by qliu21** [comment]
Thanks!

**Comment by ben-e-whitney** [comment]
@qliu21, @tugluk [says above][mgard3 comment] we can delete `mgard3`. I suggest we also delete `vanilla`, as so many changes to the code have been made that I don't think it'd be reasonable to ask Brown to fix any issues found dating back to that point.

Finally, there is `mgard`. It contains five commits not in `master`:

```console
$ git log --pretty=oneline origin/master..origin/mgard
5b14862350655a5365b2f36a566f3f89e9dd0470 (origin/mgard) Merge branch 'mgard' of https://github.com/CODARcode/MGARD into mgard
9c55b4d478eccdfcdf5c3f70f7637e59097a7f49 Fixed the number of projections for non-2^k+1 case. Setting l_target = nlevel -1
13d27f6c69c7f2bc7b3d510487013019683ae035 Merge pull request #19 from NAThompson/mgard
8e4d93ee1cc121712155852a807306f88c83dc8d Add benchmark of linear data.
c1e06c3f997a00c25165d7e8046afa098ee25202 Make benchmarks easier to read by adding symbols and forcing the compiler to keep frame pointers.
```

Chronologically:

1. c1e06c3f997a00c25165d7e8046afa098ee25202 has been obviated by subsequent changes to the makefile.
2. 8e4d93ee1cc121712155852a807306f88c83dc8d adds a benchmark and was never merged. I can cherrypick it.
3. 13d27f6c69c7f2bc7b3d510487013019683ae035 merges the preceding commit and 3d8438b6779f652b8ba443f7f4dcb0b82b1290fe, which is in `master`.
4. 9c55b4d478eccdfcdf5c3f70f7637e59097a7f49 changes a bunch of definitions of `l_target`. It was never merged, but the changes seem to have been made elsewhere:

```console
$ git show origin/master:src/mgard.tpp | grep 'l_target\s*='
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
    const int l_target = nlevel - 1;
    const int l_target = dims.nlevel - 1;
    const int l_target = nlevel - 1;
    const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
    const int l_target = nlevel - 1;
    const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
    const int l_target = dims.nlevel - 1;
    const int l_target = nlevel_new - 1;
    const int l_target = dims.nlevel - 1;
    const int l_target = nlevel_new - 1;
    const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
    const int l_target = nlevel_new - 1;
    const int l_target = dims.nlevel - 1;
  const int l_target = dims.nlevel - 1;
//   const int l_target = dims.nlevel-1;
//       const int l_target = nlevel-1;
```

5. 13d27f6c69c7f2bc7b3d510487013019683ae035 merges the preceding two commits.

So, I suggest we also delete `mgard`, and I will include 8e4d93ee1cc121712155852a807306f88c83dc8d in a future pull request.

[mgard3 comment]: https://github.com/CODARcode/MGARD/issues/34#issuecomment-547679873

**Comment by qliu21** [comment]
@ben-e-whitney  I am going through the github issues and wanted to address them as much as I can to get ready for the next release. 

I am going to delete "mgard", "mgard3", "vanilla" branch, if there is no problem, and close this.

**Comment by qliu21** [comment]
Let me delete "mgard3" and "vanilla", which are confirmed. I am closing this.

**Comment by qliu21** [comment]
Also deleting "mgard".
