### ISSUE TITLE
Storing s in compressed stream?

### ISSUE THREAD

**Issue by NAThompson** [CODARcode/MGARD#37]
When using the `s` parameter overload, if I call `mgard_compress` with `s = 1` (say), and later forget the `s` that I compressed the data with, I cannot decompress it: Calling `mgard_decompress` with an incorrect `s` or without supplying `s` leads to corrupted data.

On the TODO list, we should place the `s` parameter in the `char` stream so that we can decompress without supplying `s`.

**Comment by tugluk** [comment]
You wouldn't really forget it, but why not, it can be added to the stream.

**Comment by ben-e-whitney** [comment]
Reopening till we've either added `s` to the stream or decided against doing so.

**Comment by ben-e-whitney** [comment]
This is a long ways off, but here are some ideas for saving the compression parameters:

1. Include some sort of header in the compressed stream.
2. Output alongside the compressed stream a metadata file; the final output could then be an archive containing both the metadata and the compressed stream.
3. Use some existing self-describing file format (ADIOS' BP format, HDF5, netCDF, etc.).

In addition to `s` we'd probably want to include the shape of the data, a version number, the error tolerance, quantization parameters, etc. I don't know anything about the integration with ADIOS, but I imagine that it might be preferable to keep the metadata separate from the compressed stream until everything is ultimately dumped to disk.

**Comment by NAThompson** [comment]
I would suggest 1. In fact, should mgard have it's own file format?

**Comment by ben-e-whitney** [comment]
The reimplemented `compress` function added in 1120e92e4e9bf96cbacb9fd0f796456f9986028c returns an object containing the value of `s` used to compress the data.

```cpp
const mgard::CompressedData<N, Real> compressed = mgard::compress(hierarchy, u, s, tolerance);
std::cout << "the dataset was compressed with s = " << compressed.s << std::endl;
```

I'll leave this issue open till the changes have been merged.
