### ISSUE TITLE
Can't build with PGI because of `restrict` keyword

### ISSUE THREAD

**Issue by chuckatkins** [CODARcode/MGARD#4]
Currently unable to build with PGI because of API functions named `restrict` which is a reserved C keyword.  Renaming the API functions to something else not conflicting with a reserved keyword allows the build to be successful with PGI.

**Comment by chuckatkins** [comment]
Note that since this is part of MGARD's public API, it also prevents a downstream consumer to build with MGARD support and PGI.

**Comment by tugluk** [comment]
Solved with recent commit
