### ISSUE TITLE
Inconsistent Meaning of `s` in API

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#70]
The meaning of `s` is very confused in `mgard_api.h`. In the overloads without a `qoi` parameter, `s` determines the norm in which the error in the data is to be controlled. See, for examples, [lines 101–107 of `mgard_api.tpp`][`s` first meaning] (copied below).

```cpp
    assert(nrow > 3);
    assert(ncol > 3);
    assert(nfib > 3);


    mgard_compressed_ptr =
        mgard::refactor_qz(nrow, ncol, nfib, v, out_size, tol, s);
    return mgard_compressed_ptr;
```

In the overloads *with* a `qoi` parameter, though, the error is controlled in the `-s` norm. See, for example, [lines 150–155 of `mgard_api.tpp`][`s` second meaning] (copied below). Here, `s` determines [the norm used for the Riesz representative of the functional][Riesz representative norm calculation]. The `s` norm of the Riesz representative of the functional equals the operator norm of the functional as it acts on `H^-s`, not `H^s`. (So it's consistent, at least, that we call `refactor_qz` with `-s` – we are thinking of the data as an element of `H^-s` and the functional as an element of `(H^-s)*`.)

```cpp
    Real xi_norm = mgard_gen::qoi_norm(nrow, ncol, nfib, coords_x, coords_y,
                                       coords_z, qoi, s);
    tol *= xi_norm;
    mgard_compressed_ptr =
        mgard::refactor_qz(nrow, ncol, nfib, v, out_size, tol, -s);
    return mgard_compressed_ptr;
```

Also, why are we multiplying, instead of dividing, by the functional norm here? See Eq. (3) and the surrounding sentences in the [derived quantities paper][derived quantities paper].

@tugluk, please correct me if I'm misunderstanding something here!

[`s` first meaning]: https://github.com/CODARcode/MGARD/blob/2a3fe706638466148ac1cc3694bdcb4ebf11d864/src/mgard_api.tpp#L101-L107
[`s` second meaning]: https://github.com/CODARcode/MGARD/blob/2a3fe706638466148ac1cc3694bdcb4ebf11d864/src/mgard_api.tpp#L150-L155
[Riesz representative norm calculation]: https://github.com/CODARcode/MGARD/blob/2a3fe706638466148ac1cc3694bdcb4ebf11d864/src/mgard_nuni.tpp#L4367-L4378
[derived quantities paper]: https://epubs.siam.org/doi/pdf/10.1137/18M1208885

**Comment by tugluk** [comment]
That indeed is more or less the way I was  thinking.   Without  `qoi`, we are preserving the error in the data in  `s` norm; with  `qoi` we are preserving the error in the functional in  `s` norm.  So I kept the signs the same. 

But if you think we should be consistently computing the  `s` norm of the data, we can swap the signs. 

You are correct, we should be dividing, I'm checking this.

**Comment by ben-e-whitney** [comment]
As we've (temporarily) removed the quantity of interest overloads, this issue has been sidestepped. I'll keep it in mind when designing the replacement overloads.
