### ISSUE TITLE
Purpose of `get_lindex`

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#73]
This came up in a discussion with @qliu21 and I'm hoping @tugluk will be able to help.

`get_lindex` has the following definition (as of [54ce49e][definition]).

```cpp
int get_lindex(const int n, const int no, const int i) {
  // no: original number of points
  // n : number of points at next coarser level (L-1) with  2^k+1 nodes
  return (i != n - 1 ? std::floor(i * static_cast<double>(no - 2) / (n - 2))
                     : no - 1);
}
```

I am trying to understand why the ratio is `(no - 2) / (n - 2)` instead of `(no - 1) / (n - 1)`. My understanding is that `get_lindex` takes the index of a node in a mesh with `n` nodes and returns the index of a corresponding node in a mesh with `no` nodes. But if `n = 3` and `no = 101`, then node `1` in the `n` mesh (at, supposing the mesh is on `[0, 1]`, `0.5`) gets mapped to node `get_lindex(3, 101, 1) = 99` in the `no` mesh (almost at `1`). Is the function or my understanding of it wrong?

[definition]: https://github.com/CODARcode/MGARD/blob/54ce49eafc88cb8bfb984f2186276b9138f79bb0/src/mgard_mesh.cpp#L36-L41

**Comment by tugluk** [comment]
Using 1 instead of 2 works of course, I have to check my notes to see why I
went with 2 .

Your understanding is correct, however the case  n = 3 and no = 101 will
not occur, because n is defined as  2^( floor( log2(no - 1) ) ) + 1  (i.e
closest 2^(k+1) int less than no).

In your example if no=101, n=65, so node 1 is mapped to 1.

I'll try to be clearer tomorrow morning.

**Comment by ben-e-whitney** [comment]
For a example with more realistic numbers, take `n = 5` and `no = 6`. If `i = 3`, ratio `(no - 2) / (n - 2)` gives index `3` while ratio `(no - 1) / (n - 1)` gives (assuming exact arithmetic) index `4`. You can get more examples using this script:

```python
import math

def n_from_k(k):
    return (1 << k) + 1

def index(n, N, i, subtrahend):
    return math.floor(i * (N - subtrahend) / (n - subtrahend))

for k in range(2, 5):
    n = n_from_k(k)
    print(f'n = {n}')
    for N in range(n + 1, n_from_k(k + 1)):
        print(f'  N = {N}')
        for i in range(n - 1):
            x = math.floor(i * (N - 2) / (n - 2))
            y = math.floor(i * (N - 1) / (n - 1))
            if x != y:
                print(f'    i = {i}: {x} vs. {y}')
```

What exactly is this function used for? My impression is that it's used when interpolating a function to a '`2^k + 1`' grid, but then I don't get why `std::floor` is used instead of rounding (and wouldn't we want to interpolate, anyway, rather than 'snapping' to a different node?).

**Comment by tugluk** [comment]
Oh shoot, this would be more helpful maybe:

level   physical index     logical index
3        0, 1, 2, 3, 4, 5
2        0, 1, 2, 4, 5          0, 1, 2, 3, 4
1        0, 2, 5                  0, 2, 4
0        0, 5                      0, 4

**Comment by ben-e-whitney** [comment]
OK, so if `no = 6` and `n = 5` then the ratio `(no - 2) / (n - 2)` gives the subset `{0, 1, 2, 4, 5}` and the ratio `(no - 1) / (n - 1)` gives the subset `{0, 1, 2, 3, 5}`. Did you ever find your notes? I am trying to document this function and would like to explain why it generates the specific subset it does.
