### ISSUE TITLE
Unused Parameters in `qoi_norm` Subroutines

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#74]
[60ef1e4][commit] pulls the `qoi_norm` functions into a separate file. (For posterity, since I may rebase the branch, changing the commit hash, this is my commit dated 2020-03-03T14:31:36-05:00.) Compiling reveals a number of unused parameters and variables. Put the following

```cpp
#include "mgard_norms.hpp"

float qoi(int, int, int, float *) { return 0; }

int main() {
  const std::vector<float> coords = {1, 2, 3, 4, 5};
  const int N = coords.size();
  const float s = 0;
  mgard::qoi_norm(N, N, N, coords, coords, coords, qoi, s);
  return 0;
}
```

into a file `unused.cpp` in the root of the repository and compile like so.

```console
$ g++ -Wall -Wextra -c -Iinclude -o unused.o unused.cpp
```

I imagine that the unused variable warnings are not serious, caused by leftover code that can be deleted, but the unused parameter warnings raise alarm bells for me. In particular, none of `project_2D`, `project_2D_non_canon`, and `project_3D` use `v`, which appears to be the function being projected. Possibly the values have been copied into one of the temporary buffers when these functions are called?

@tugluk, is this right? Even if there's a bug here, I think we can hold off on fixing it for now, since we should probably be rewriting the projection functions before too long.

[commit]: https://github.com/CODARcode/MGARD/commit/60ef1e489341f03220c18709945d66e7b531946f

**Comment by tugluk** [comment]
Yes, the data should be copied to the work array, v* probably is a
leftover. Will check to be sure, thanks.
