### ISSUE TITLE
Scaling Difference Between Mass Matrix and Inverse

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#79]
The 1D mass matrix on a uniform grid has diagonal `h / 6 * (2, 4, …, 4, 2)` and sub- and superdiagonal `h  / 6 * (1, …, 1)`. [`mass_matrix_multiply`][mass_matrix_multiply] uses scaling `h = 3`, while [`solve_tridiag_M`][solve_tridiag_M] uses scaling `h = 6`. This can be seen by compiling and executing the script below with the following commands.

```console
$ git checkout 5630dc6c21d24dfbe22f323d07d6cf702fedc79d
$ make lib/libmgard.a
$ g++ -g -fno-omit-frame-pointer -O3 -march=native -ffast-math -fno-finite-math-only -std=c++11 -fPIC -Iinclude -c -o obj/scaling.o scaling.cpp
$ mkdir --parents bin
$ g++ -g -fno-omit-frame-pointer -O3 -march=native -ffast-math -fno-finite-math-only obj/scaling.o lib/libmgard.a -lz -ldl -o bin/scaling
$ bin/scaling
```
@tugluk, is there some reason for this, or is it just an oversight?

[mass_matrix_multiply]: https://github.com/CODARcode/MGARD/blob/5630dc6c21d24dfbe22f323d07d6cf702fedc79d/src/mgard.tpp#L1148-L1163
[solve_tridiag_M]: https://github.com/CODARcode/MGARD/blob/5630dc6c21d24dfbe22f323d07d6cf702fedc79d/src/mgard.tpp#L1165-L1213

(Separately, `solve_tridiag_M` throws an exception when `l` is zero. I will fix that.)

```cpp
#include <cstddef>

#include <iostream>
#include <vector>

#include "mgard.h"

std::ostream & operator<<(std::ostream &ostream, const std::vector<float> &v) {
  ostream << "[";
  const std::size_t N = v.size();
  for (std::size_t i = 0; i + 1 < N; ++i) {
    ostream << v.at(i) << ", ";
  }
  ostream << v.back() << "]";
  return ostream;
}

int main() {
  std::vector<float> v = {2, -1, 4};
  const int l = 1;

  std::cout << " v = " << v << std::endl;

  mgard::mass_matrix_multiply(l, v);
  std::cout << "Mv = " << v << std::endl;

  mgard::solve_tridiag_M(l, v);
  std::cout << " v = " << v << std::endl;

  return 0;
}
```

**Comment by tugluk** [comment]
Good point, the solver was intended to be used in the projection, the
factor of 2 in the scaling takes care of the change in h between levels. It
might be better to move the factor of 2 outside the solver, I agree.

**Comment by ben-e-whitney** [comment]
Ah, yes, I see. The scaling lets the following compute the projection.

```cpp
mass_matrix_multiply(l, v);
restriction(l + 1, v);
solve_tridiag_M(l + 1, v);
```

I will either add a note explaining it or rescale in the functions. Thanks.

**Comment by tugluk** [comment]
Thank you, for bringing this up! I'm sure it will be beneficial to
make a note so people won't be confused.
