### ISSUE TITLE
Support passing user-specified data to qoi metrics in a flexible way

### ISSUE THREAD

**Issue by robertu94** [CODARcode/MGARD#84]
Would it be possible to get a void* parameter added to the qoi function pointer argument to mgard_compress as well a void* parameter to the mgard_compress to allow the user to pass some stack/heap allocated reference data rather than statically to be used when computing the quality of interest? This would be helpful in integrating metrics from Z-checker/LibPressio.

the proposed new signature would be:

```cpp
template <typename Real>
Real mgard_compress(int n1, int n2, int n3, Real (*qoi)(int, int, int, Real *, void* /*user_data will be passed here for all invocations*/),
                    Real s, void* user_data);
```

where the user_data argument to mgard_compress would get passed unmodified to qoi when it is called in qoi_rhs? This would allow me to write a qoi funcion like so and have it be thread safe (libpressio_metrics objects are thread-safe as long as you have seperate objects for each thread).

```cpp
struct pressio_mgard_qoi_args {
     pressio_metrics* metrics;
     const char* key;
}

double pressio_qoi (int rows, int cols, int fibs, double* data, void* pressio_metrics_ptr) {
     pressio_metrics* metrics = ((pressio_mgard_qoi_args*)pressio_metrics_ptr)->metrics;
     const char* key = ((pressio_mgard_qoi_args*)pressio_metrics_ptr)->key;
     pressio_data* data_ref = pressio_data_new_nonowning(data, ...); //doesn't copy the data, just create the metadata so libpresiso can understand it
     pressio_metrics_evaluate(metrics, /*we don't want to reset the uncompressed  data*/ nullptr, /*we only have perturbed data*/data_ref);  //evaluates a libpressio-configured metric, available in libpressio v 0.41.0
     pressio_options* metrics_results = pressio_metrics_get_results(metrics);
     double ret;
     pressio_options_get_double(options, key, &ret);
     pressio_options_free(metrics_results);
     pressio_data_free(data_ref);  //free the metadata
     return ret;
}
```

Alternatively, I could do the same thing with a global pressio_metrics object, but that gets messy for several reasons and couldn’t be thread safe due to limitations in libpressio.

**Comment by ben-e-whitney** [comment]
I am in favor of this, but we need to think a bit about how we want to do it.

One option: do this without adding another `mgard_compress` overload. Separately calculate the norm of the QoI using [these functions][QoI norm functions] and have all the QoI compression calls go through [this function][compression using QoI norm]:

```cpp
template <typename Real>
unsigned char *mgard_compress(Real *data, int &out_size, int n1, int n2, int n3,
                              Real tol, Real norm_of_qoi, Real s);
```

(Separate issue: as long as we're templating on the datatype, I think we might as well template on the dimension. I'm slowly rewriting the internal functions in this way; we'll see if the API is ever changed to match.)

Reasons to prefer the style where the norm of the QoI is separately calculated:

1. The only thing the compressor uses about the QoI is its norm. (I can envision a future where this is not the case; separate issue.) There would be no need for these `qoi` overloads if we just included `qoi_norm` in the API (currently it's in `mgard_mesh.hpp`).
2. The calculation of the QoI norm is very expensive. (I don't know of a way to speed it up; there might be one). Unless the norm is passed in, if you, for example, want to compress a dataset multiple times with the same QoI and the same `s` but different error tolerances, you will be forced to repeat a very expensive calculation unnecessarily.
3. The `s` norm of a QoI is calculated as follows. Virtually all of the work comes before the final step, and only that step uses `s`. So if you want to calculate the norm of the QoI for a variety of `s` values, you will again be forced to repeat a very expensive calculation unnecessarily.
    1. Evaluate the QoI at every element of a basis for the function space.
    2. Invert a mass matrix to find the Riesz representative of the QoI
    3. Decompose the Riesz representative into a collection of orthogonal components.
    4. Find the `L^2` norms of those components.
    5. Using `s`, sum those norms to find the norm of the QoI.

`qoi_norm` also has this problem; another separate issue.

The main downsides I see with this approach are

1. It forces the user to compute the norm separately.
2. If and when the compressor uses more information about the QoI than its norm, we'll have to change `mgard_compress` again.

Even in that case, though, I think we'll want to pass some sort of `QuantityOfInterest` object, maybe containing the Riesz representative of the QoI, so we don't repeat more work than necessary when compressing with different `s` values.

Perhaps it would be better to pass the QoI as a [`std::function<Real (Real const * const)>`][std::function] object? Then the same `mgard_compress` overload could be used for simple function pointers and more general function objects holding data. We'd have to do something else for it to be callable from C, though.

[QoI norm functions]: https://github.com/CODARcode/MGARD/blob/7310894a558083dc6caea2deb74be869427a7f6e/include/mgard_norms.hpp#L10-L52
[compression using QoI norm]: https://github.com/CODARcode/MGARD/blob/7310894a558083dc6caea2deb74be869427a7f6e/include/mgard_api.h#L133-L152
[std::function]: https://en.cppreference.com/w/cpp/utility/functional/function

**Comment by robertu94** [comment]
@ben-e-whitney is there any update on this?

**Comment by ben-e-whitney** [comment]
@robertu94 Apologies for the delay, and thank you for the reminder.

> This wouldn't bother me from a libpressio perspective, the only question is under what circumstances can I cache the QOI norm? If the data or the qoi function changes, I guess the norm_of_qoi also need to be recomputed. What about tolerance? Are there other things that should trigger re-computation?

If the QoI function changed, yes, we'd have to recompute the norm. If the `void *` data changed, that'd count as the QoI changing, so we'd again recompute. If the data you're *compressing* changed, though, there'd be no need to recompute. Nor would we need to recompute if the error tolerance changed. If the smoothness parameter (`s`) changed, we'd have to recompute, but, as noted above, it'd be quite cheap (only the final step in the calculation would need to be redone). I think that's about it.

What do you think about the following plan?

1. I add the new overloads (immediately marked as deprecated) and function bodies and submit a pull request to `master`.
2. You are able to use the overloads quickly, without waiting for the whole QoI rethink.
3. Eventually (months away, probably), a `QuantityOfInterest` class is introduced and the signatures change.
4. When it's convenient, you upgrade and change your calling code.

(@qliu21, does this look OK to you?)

Thank you for the tip about `std::function`, by the way. It lead me to some interesting reading. Appreciate your patience and suggestions, as always!

**Comment by robertu94** [comment]
@ben-e-whitney that would work for me!

**Comment by robertu94** [comment]
@ben-e-whitney ping

**Comment by ben-e-whitney** [comment]
@qliu21, does this look OK to you?

@robertu94, thank you again for your patience and persistence! Please always feel free to bother me!

**Comment by ben-e-whitney** [comment]
@robertu94 Working on this now. Hoping to be done on Thursday. Merging into the main branch is going to take a while (we'll have to wait for #86), but at least you'll be able to start playing around with it.

There will be a change to the default node spacing (introduced by an earlier, unrelated commit in the branch I'm building this on top of): where previously `n` nodes in a particular dimension would be spaced uniformly across `[0, n - 1]` (so that the distance between adjacent nodes was `1`), now they are spaced uniformly across `[0, 1]` (so that that distance is `1 / (n - 1)`). Hope this doesn't cause too many issues for you. Later on you'll be able to specify your own spacings here, as with the compression routines.

**Comment by qliu21** [comment]
@ben-e-whitney it looks like for some reason, I do not receive these notifications automatically. Sorry about that - let me read through this thread and will get back to you.

**Comment by robertu94** [comment]
@ben-e-whitney I see that #86  was merged,  Does that mean that the QOI changes have been made?

**Comment by robertu94** [comment]
ping!

**Comment by ben-e-whitney** [comment]
Sincere thanks for the reminder. I have just opened a pull request (#89) that (among many other changes, including a few to the API) adds functions for computing the norm of a quantity of interest function accepting a `void *` parameter. See de07e4cd9f7ce59de7ad111b1833b6bc53978162. The new functions are declared in `include/TensorNorms.hpp`. You can use them like this:

```cpp
#include <cstdlib>

#include "mgard_api.h"
#include "TensorNorms.hpp"

float pressio_qoi(int rows, int cols, int fibs, float* data, void* pressio_metrics_ptr);

int main() {
  const int n1 = 10;
  const int n2 = 5;
  const int n3 = 8;
  const float s = 0.5;
  const float tolerance = 0.01;

  void* pressio_metrics_ptr;
  // This computes the norm of the Riesz representative in the `s` norm.
  const float norm_of_qoi = mgard::norm(n1, n2, n3, pressio_qoi, s, pressio_metrics_ptr);

  float * const data = static_cast<float *>(std::malloc(n1 * n2 * n3 * sizeof(*data)));
  int out_size;
  // The data is internally compressed with smoothness parameter `-s`. See the
  // note in `mgard_api.h`.
  unsigned char * const p = mgard_compress(data, out_size, n1, n2, n3, tolerance, norm_of_qoi, s);

  std::free(p);
  std::free(data);
  return 0;
};
```

The new functions are already marked as deprecated. Eventually I hope to add some sort of `QuantityOfInterest` class, as mentioned above.

Will this be good enough for now? Happy to make changes if there's a problem. Thanks for the suggestion.

**Comment by robertu94** [comment]
@ben-e-whitney The header "TensorNorms.hpp" is not installed with MGARD on cmake install, could this header be exposed?
