### ISSUE TITLE
Memory Leaks in Huffman Code

### ISSUE THREAD

**Issue by ben-e-whitney** [CODARcode/MGARD#94]
I get some minor memory problems when using the Huffman code. Mostly they are just memory leaks, but there is also a misaligned load. To reproduce, run the following. (`sample_r_B_0.5_26.dat` can be found [here][sdrbench].)

```console
$ git checkout abd79fc440841eab8a194fe374e8d1146bcd35b0
$ DEBUG=1 make lib/libmgard.a bin/
$ g++ -g -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -std=c++11 -fPIC -Iinclude  -c -o obj/test_1d.o tests/test_1d/test_1d.cpp
$ g++ -g -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined  -fsanitize=address -fsanitize=undefined   obj/test_1d.o lib/libmgard.a -lz -ldl -o bin/test_1d
$ dd count=1 < sample_r_B_0.5_26.dat > sample.dat
$ bin/test_1d sample.dat 0.05 2> stderr.txt
```
[Here][stderr] is the output I get.

[sdrbench]: https://sdrbench.github.io/
[stderr]: https://github.com/CODARcode/MGARD/files/5228000/stderr.txt

**Comment by qliu21** [comment]
Will look into misaligned issue next.

**Comment by qliu21** [comment]
Fixed the alignment issue.
